name: flannel-images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: .\build.ps1
