name: flannel-images

on:
  push:
    paths:
      - "kubeadm/flannel/**"
      - ".github/workflows/flannel.yml"

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        ./build.ps1 -Image vleschenko/flannel -Push
