name: flannel-images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Build images
      run: |
        cd ~/.docker
        ls -a -l
        mkdir manifests
        docker manifest create vleschenko/flannel:0.13.0 --amend vleschenko/flannel:0.13.0-nanoserver-1809 --amend vleschenko/flannel:0.13.0-nanoserver-1903 --amend vleschenko/flannel:0.13.0-nanoserver-1909 --amend vleschenko/flannel:0.13.0-nanoserver-2004
        cd manifests
        ls -a -l

