name: flannel-images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Build images
      run: |
        cd ~
        ls -a -l
