name: flannel-images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Build images
      run: ./build.ps1 -BuildID $env:GITHUB_RUN_ID
    - name: View images
      run: docker images