name: flannel-images

on:
  push:
    paths:
      - "kubeadm/flannel/**"
      - "kubeadm/buildx.psm1"
      - ".github/workflows/flannel.yml"
    branches:
      - master
  pull_request:
    paths:
      - "kubeadm/flannel/**"
      - "kubeadm/buildx.psm1"
      - ".github/workflows/flannel.yml"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/flannel
    steps:
    - uses: actions/checkout@v2
    - name: Build and push images
      if: ${{ github.event_name == 'push' }}
      run: |
        echo ${{ secrets.AZURE_DOCKER_SECRET }} | docker login -u ${{ secrets.AZURE_DOCKER_USERNAME }} --password-stdin
        ./build.ps1 -push -image vitaliyorg.azurecr.io/k8s/flannel
    - name: Build images (without push)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ./build.ps1 -image vitaliyorg.azurecr.io/k8s/flannel
