name: kube-proxy-images

on:
  push:
    paths:
      - "kubeadm/kube-proxy/**"
      - ".github/workflows/kubeproxy.yml"

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: pwsh
        working-directory: ./kubeadm/kube-proxy
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        ./build.ps1 -image vleschenko/kube-proxy -push
